### ISSUE TITLE
Some design improvements !

### ISSUE THREAD

**Issue by ctseo** [PromInc/organic-search-analytics#12]
I dont know very good to use GIT, i didnt know to add pull requst ( by comparing my files with your ), and i've added here the changes in a zip file.
http://www.filedropper.com/modified

**Comment by PromInc** [comment]
Thanks for providing these improvements.

I have integrated much of your CSS into my dev version.  I had hoped to be able to push it today, but apparently I don't know GIG well enough either and something funky happened.  So it'll be some time next week before I get the code ready.

**Comment by PromInc** [comment]
Thank you @ctseo for these contributions.  I have added most of your updates to the codebase where I felt appropriate!!  (this was overdue...  ha!)

Release 2.3.0
