### ISSUE TITLE
Report Table Updates

### ISSUE THREAD

**Issue by PromInc** [PromInc/organic-search-analytics#15]
Adding a request from @ctseo from Issue #10 

> You should add on top or bottom of table the total impressions,clicks, avg position and avg CTR.
> ...
> You sould add a filter by how many results to display per page... becouse the browser can crash.
> I found a little bug: if you have a long query. Please see the print screen. (in Issue #10)

One more that I'll add to this list my self is to be able to toggle Sort By and Sort Direction of the table by clicking on the heading of each column.

**Comment by ctseo** [comment]
Yes. I forgot this option !!!
