### ISSUE TITLE
Report Filtering by Specific Words

### ISSUE THREAD

**Issue by PromInc** [PromInc/organic-search-analytics#16]
Adding a request from @ctseo from Issue #10 

> Next update pls add this... and the posibility to search by url to see the queries ( even if you want exclude some queries).
> 
> Here some steps : 
> 1. Add URL, and show queries, clicks, impressions by specific dates
> 2. Add URL, exclude some queries ( that start/contains specific words - regex -)

@ctseo - can you expand on this request more?  I must not be fully understanding what you are looking for, I feel most of these features already exist.

When you refer to **URL** - is that different than the **Domain** that is already available in the report settings?

The tool currently allows you to view specific queries via the **Query** and **Query Match Type** (**Broad** = contains, **Exact** = exactly matches).  It sounds like you are asking for an additional radio button to choose include or exclude the **Query**?

![osa-domain-query](https://cloud.githubusercontent.com/assets/7319505/11844181/050ba47e-a3d3-11e5-82fe-eb0076609b0f.JPG)

**Comment by ctseo** [comment]
Well... if you look at Google Search Console, you will see  the secound field ( Pages ).
There you can see all keywords (queries) that contain specific URL.
We need this option to filter our queries... :) it's more easy if we can filter this by page !

**Comment by PromInc** [comment]
Understood.  First page level data needs to be captured, as requested in #13.
