### ISSUE TITLE
focus on the import - make the database optional

### ISSUE THREAD

**Issue by Sawascwoolf** [PromInc/organic-search-analytics#3]
Hi,

I think every body who whants to use your code ist capable of programming and therefore is able to handle the received data on its own.
I'm currently programming my own small keywordtool and I use your code as datasource, but your code doesn't offer a function for receiving plain results, but for directly saving it to the database.
It's working now, but I think my hint will help to improve your project.

So please redesign the project, that the main focus is on retreiving the data and introduce functions for

``` php
function fetchDataForWebsiteFromSearchAnalytics($website,$start, $end = NULL) {
if ($end === NULL) {
$end = $start;
}
```

and

``` php
function findWebsitesWithAvailablePermissions() {

}
```

You could keep the database implementation as example.

**Comment by PromInc** [comment]
Hello @Sawascwoolf,

I appreciate your comments and help and certainly welcome suggestions towards improvements.

I am aware that this code is at this time basic and in need of some future enhancements - I certainly have a large undocumented wish list of things I'd like to build into it and it will certainly come in time.  One of which is a method to automate the capturing of data so this can become a hands-free tool until you need the reporting.

My intention and motivation for building this tool is simply for the purpose of archiving data beyond the 3 months that Google provides it.  I am interested in long term SEO trends and shifts, and having this data beyond 3 months can help to monitor and gauge performance of a website over time.  Also, my intention was for this to be more focused at what I call the "savy marketer" - the person that knows enough code to set this up or at least has a tech guy handy enough to do this for them.  From there, the GUI would be intuitive and powerful enough for a person to quickly get in, get some information, and get out.

I wanted to share that background and direction with you to help understand why it is built the way it is built.

That said, I am open to improvements, however I apologize but I'm not sure that I'm fully understanding what features you are requesting.  If I understand correctly, you really just want to be able to access data but are not interested in the historical factor of it (as you mention not needing the database).  If this is the case, why not just use Google Search Console to access the data that they provide?

I'm also wondering if you are using a current release that includes the reporting functionality.  Through the reporting you do get a view of your data on a day by day basis - clicks, impressions, etc. and this can be narrowed down by site, keyword, device type, etc.

**Comment by Sawascwoolf** [comment]
Hi,

I love playing around with the information I can extract for my projects. The more data I receive the more fun :D

I've already built a tool where I had to import the csv-files manually. So I've got a database structure and I just wanted to use your project as a datasource. It would be a overhead to use your tool to import it to a database first in order to grab the data from there and move it to my db.

Your project contains three parts:
- fetch Data from google (100% want to use this)
- save Data directy to DB (50% want to use this)
- perform the same analytics as your code offers (25% want to use this)

Currently your code offers easy functions to import the data into the db, but it doesn't offer ready to use functions for just retrieving the result from google. I had to copy about 30 lines of code for just getting the result as PHP-Array while it would be 1-line of code to import the whole stuff into the db.

I could imagine three possible solutions for my problem:
- (best) move the request part to a seperate project
- (better) redesign your whole project and make the request the main part and move the rest to an example
- (ok) create callable functions for requesting data directly from google

**Comment by PromInc** [comment]
Thank you for your explanation.

So really you are looking for a CSV output of the Google data - that's the primary function you are in search of.

At this time, re-developing this project into a separate project or doing a redesign to take away the database is counter-intuitive to what the goals of this project are and my needs.  This repo is really just me sharing code I've written to help my marketing efforts.

While I'm not opposed to having an export to CSV option as a secondary option to importing to the database (maybe this is a new page/option?), this does not top my priority list at this time as this is a default feature that is already provided by Google Search Console Analytics.

If this is something you'd really like to see added to this project feel free to submit a pull request with this function in it.  If you'd like to go that route, here is some Javascript code (utilizing jQuery) that can be used for the export to CSV portion - this is some code that I've copied from another project I've worked on, so some of the variable names and comments might not make much sense to this project, but shouldn't take much effort to adapt this code for this function.

As the data is captured from Google, it'll need to be put into a javascript array (arrayOfSearchAnalytics in below code) that then gets parsed into the CSV file.

``` javascript
/* Export to CSV */
function exportToCSV() {
    /* Javascript CSV Output information */
    /* http://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side */

    var csvLinesPerURL = {};
    $.each(arrayOfSearchAnalytics, function(iURL,dataURL) {
        /* Determine how many lines are needed for each URL */
        csvLinesPerURL[iURL] = 0;
        $.each(dataURL, function(iElm, dataElement){
            if( dataElement.length > csvLinesPerURL[iURL] ) { csvLinesPerURL[iURL] = dataElement.length }
        });
    });

    /* Start generating the CSV Output Data */
    var csvOutput = "";
    /* Put header row into CSV Output */
    $.each(allHeaders, function(iHeader,dataHeader) {
        csvOutput += '"'+dataHeader+'"';
        if( iHeader != Object.keys(allHeaders).length-1 ) {
            csvOutput += ',';
        } else {
            csvOutput += '\r';
        }
    });


    /* Put data into CSV Output */
    /* For each URL */
    $.each(arrayOfSearchAnalytics, function(iURL,dataURL) {
        /* For the total number of lines of output needed for each URL */
        for(var line=0; line < csvLinesPerURL[iURL]; line++) {
            /* For each column, add data */
            $.each(allHeaders, function(iHeaders, dataHeaders){
                if( !arrayOfSearchAnalytics[iURL][dataHeaders] || arrayOfSearchAnalytics[iURL][dataHeaders][line] == undefined ){
                    csvOutput += '""';
                } else {
                    csvOutput += '"'+arrayOfSearchAnalytics[iURL][dataHeaders][line]+'"';
                }
                /* Add comma or new line */
                if( iHeaders != Object.keys(allHeaders).length-1 ) {
                    csvOutput += ',';
                } else {
                    csvOutput += '\r';
                }
            });
        }
    });

    var fileName = "search_analytics_export.csv";
    downloadFile(fileName, 'data:text/csv;charset=UTF-8,' + encodeURIComponent(csvOutput));
}
```

**Comment by PromInc** [comment]
Also as an FYI - my current priority is to integrate Bing webmaster tools into this, and most likely follow that up with enhancing the reporting features.  I'm sure at that time I'll add CSV exports to the reports that are generated, but again this will require storing data into the database.

Just wanted to share where I'm heading with this to help you decide how to best achieve you project needs.

**Comment by Sawascwoolf** [comment]
Hi,

you don't get what I mean - I should improve my language skills I think.
I've implemented the requested function myself now, perhaps you'll see what I meant by reading my function. 
The function doesn't implement all of the api-features, but it fulfills my needs.
In order to use this function you need to change the 2 lines around the DRUPAL_ROOT constant.

``` php
function ltw_keywordtool2_fetchDataFromGoogle($options) {
    //<editor-fold>
    // Test necessary elements
    if (!isset($options["website"]) || !isset($options["startDate"])) {
        return FALSE;
    }
    $website = $options["website"];
    $startDate = $options["startDate"];
    $defaultOptions = array(
        "endDate"           => $startDate,
        "dimensions"        => array('query'),
        'rowLimit'          => 5000,
        'searchTypes'       => array("web"),
        'aggregationType'   => 'auto',        
    );
    foreach ($defaultOptions as $key => $value) {
        $$key = (isset($options[$key])) ? $options[$key] : $value;
    }    
    //</editor-fold>
    //<editor-fold defaultstate="collapsed">
    $path = DRUPAL_ROOT . '/sites/all/libraries/organic-search-analytics-master/';
    require_once($path . 'inc/code/globalIncludes.php');
    /* Authorize Google via oAuth 2.0 */
    $gapiOauth = new GAPIoAuth();
    $client = $gapiOauth->LogIn();

    /* Load Google Webmasters API */
    $webmasters = new Google_Service_Webmasters($client);

    /* Load Search Analytics API */
    $searchAnalyticsRequest = new Google_Service_Webmasters_SearchAnalyticsQueryRequest($client);

    /* Prepare Search Analytics Resource */
    $searchanalytics = $webmasters->searchanalytics;

    /* Build Search Analytics Request */
    $searchAnalyticsRequest->setDimensions($dimensions);
    $searchAnalyticsRequest->setRowLimit( $rowLimit ); /* Valid options: 1-5000 */

    /* Set date for Search Analytics Request */
    $searchAnalyticsRequest->setStartDate( $startDate );
    $endDate = ($endDate) ? $endDate : $startDate;
    $searchAnalyticsRequest->setEndDate( $endDate );
    /* Loop through each of the search types */
    //</editor-fold>
    $searchAnalyticsRequest->setAggregationType($aggregationType);

    $results = array();
    foreach( $searchTypes as $searchType ) {
        /* Set search type in Search Analytics Request */
        $searchAnalyticsRequest->setSearchType( $searchType );

        /* Send Search Analytics Request */

        $searchAnalyticsResponse = $searchanalytics->query( $website, $searchAnalyticsRequest);
        //dsm($searchAnalyticsResponse->rows);
        foreach( $searchAnalyticsResponse->rows as $recordKey => $recordData ) {
            //dsm($recordData["keys"]);
            $temp = array(
                "impressions"       => $recordData['impressions'],
                "clicks"            => $recordData['clicks'],
                "ctr"               => $recordData['ctr'],
                "position"          => $recordData['position'],
                "searchType"        => $searchAnalyticsRequest->getSearchType(),
                //"keys"              => $recordData["keys"],
            );
            $results[] = ($recordData["keys"]) ? array_merge($temp,array_combine($dimensions,$recordData["keys"])) : $temp;
            //break;
        }

    }
    return $results;
}
```

Example usage of this function:

``` php
$options = array(
        'website' => 'www.fck-handball.de', 
        'startDate' => '2015-07-01',
        'endDate' => '2015-09-05',
        'dimensions' => array('query','page'),
        'aggregationType' => 'byPage'
    );
    $data = ltw_keywordtool2_fetchDataFromGoogle($options);
```

If I would be you I would replace the call of _DataCapture::downloadGoogleSearchAnalytics_ in _data-capture-run.php_ with _WMTimport::importGoogleSearchAnalytics_ and use my function above inside it.

With these changes users of your complete tool won't recognize any changes, but developers like me could just use the "raw" result fetched from google.

**Comment by PromInc** [comment]
Thank you for the explanation and code example.  Here is what I did.  I just published a new branch that I think accomplishes what you are requesting while keeping some long term goals I'm hoping to achieve in mind.
[Branch - Enhanced Data Capture](https://github.com/PromInc/organic-search-analytics/commit/7b89126025f48c5bfd1a0f3c6c6d0ed59911de41)

I urge you to try this out and let me know if it's doing what you are looking for before I commit it to the master.

I essentially utilized the concept your code snippets were doing (thank you for providing) and hope that this will help you in your goal.  I did consider implementing all of your suggestions, and while I didn't test putting the code in place, I couldn't exactly follow how all this pieces together...

But here is what I did and hope it suffices for what you are looking for.

I've created two modes for what to do with the data - `import` or `return`.  `import` functions as it did prior - importing to the database.  `return` is a new mode however that does a var_dump to the `data-capture-run.php` script.  I'm open to modifying this as you see necessary.

I adopted your array method of specifying what the API request looks like, but structured it just slightly different.  There are default settings, and then they can be modified via query parameters when calling to `data-capture-run.php`  This would allow you to set a custom `row_limit` or `dimensions`.  I started to build the ability to add in filtering (which correlates to issue #4), however I am apparently not passing data to the API correctly just yet and need to further explore this.  I'd love for your input/help here as this isn't really a feature I foresee myself implementing too much, rather I think it'll be something that you are looking for and would allow for custom requests to the tool.  Once this is sorted out, groups and aggregationType would need to be implemented as well.

Lastly, I need to point out that one other change was made.  Requests to `data-capture-run.php` now require that the `type` (data source) be specified in the request.  This is in preparation for adding Bing Webmaster data.  This is automatically set when using the GUI, but when making a manual request to `data-capture-run.php` the query parameter `type=googleSearchAnalytics` needs to be added.

**Comment by PromInc** [comment]
I figured out the `filters` and `aggregationType` to this [Enhanced Data Capture](https://github.com/PromInc/organic-search-analytics/commit/7b89126025f48c5bfd1a0f3c6c6d0ed59911de41) just now.

Please test this to ensure that it's pulling data as you expect.

I haven't figured out what the groupType does even in the API explorer, so not sure how to verify if I'm implementing it correctly.

**Comment by PromInc** [comment]
I should note that I figured out the filtering issue thanks to [this post](https://github.com/google/google-api-php-client/issues/641#issuecomment-139565872).

**Comment by PromInc** [comment]
FYI - these changes have been committed to the Master branch now and are a part of the newest release, 2.0.0.

**Comment by Sawascwoolf** [comment]
Since I've implemented the function myself now and I'm currently very busy I can't run tests on this but I took a look at your source code. I think you've now fulfilled the request 
~~(ok) create callable functions for requesting data directly from google~~
from
https://github.com/PromInc/organic-search-analytics/issues/3#issuecomment-138381527

**Comment by PromInc** [comment]
Glad to hear that I was able to accomplish your goals.  I hope this utility continues to help you for your needs.  Thank you for helping to make it better!
