### ISSUE TITLE
default all tables to utf8-generic

### ISSUE THREAD

**Issue by nekromoff** [PromInc/organic-search-analytics#35]
currently, they use outdated  (like 20 years outdated) latin-1 coding.

**Comment by PromInc** [comment]
Thank you for the suggestion @nekromoff - this is actually part of an update/release that is nearly ready to go live.  Just working out the last few bugs at this point.

- [Upgrade Script](https://github.com/PromInc/organic-search-analytics/blob/Page-Level-Reporting/organic-search-analytics/upgrade.php#L87)
- [Initial DB Installation](https://github.com/PromInc/organic-search-analytics/blob/Page-Level-Reporting/organic-search-analytics.sql)

**Comment by PromInc** [comment]
Duplicates #32
