### ISSUE TITLE
try & catch block for Fatal API Errors + extend sleep period between API calls

### ISSUE THREAD

**Issue by nekromoff** [PromInc/organic-search-analytics#40]
Use try / catch blocks to block displaying of Fatal errors and rather display user friendly error message about quota hit + automatically slow down each following API call by 0.5 seconds...

Example:
> Fatal error: Uncaught Google_Service_Exception: Error calling POST https://www.googleapis.com/webmasters/v3/sites/https%3A%2F%2Flunasedacky.sk%2F/searchAnalytics/query: (403) Search Analytics quota exceeded. Learn about usage limits: https://developers.google.com/webmaster-tools/v3/limits. in /var/www/html/downloads/organic-search-analytics/apis/Google/Http/REST.php:110

**Comment by PromInc** [comment]
Great suggestion @nekromoff - Thanks!  Coming soon!
