### ISSUE TITLE
Error authorizing your API connection

### ISSUE THREAD

**Issue by Ninjataktikz** [PromInc/organic-search-analytics#46]
Hey Brian,

I got an issue.

So I have 2 URLS (Discussions / Support). For Discussion it pulled in all the data no issues what so ever but when it got to the Support Data. I got the following error. I know everything is good on my side because it use to work in the past.

Here is what I get now

> There was an error in authorizing your API connection.

Thanks

**Comment by Ninjataktikz** [comment]
I figured it out.

Just FYI for those who get similar errors.

It's because the service account was deleted from the admin users under Google Search Console and by adding it again it fixed it.

Thanks.

**Comment by PromInc** [comment]
Glad to hear you were able to resolve this issue.  Thank you for documenting what the solution was.
