### ISSUE TITLE
Don't stop data download on error

### ISSUE THREAD

**Issue by nekromoff** [PromInc/organic-search-analytics#47]
Currently, if data capture script fails (500 internal error), the whole process of data download must be manually restarted.

I recommend to wait e.g. 1 second and then retry automatically.

(working CRON data download will make this and similar issues irrelevant)

**Comment by PromInc** [comment]
Can you explain under what scenario you are receiving a `500 internal error`?  I'm curious to know more about this issue.

Also, I have updated the repo to include a method for capturing via CRON.  Update to version 2.5.2 (current master version).

A rudimentary explanation of how to run the cron scripts can be found in the [Wiki - CRON](https://github.com/PromInc/organic-search-analytics/wiki/CRON)
