### ISSUE TITLE
CRON Functionality

### ISSUE THREAD

**Issue by PromInc** [PromInc/organic-search-analytics#7]
I'm self-opening an issue following a comment left on [my blog post](http://promincproductions.com/blog/google-api-access-google-search-analytics-from-google-search-console/) regarding utilizing a CRON job to trigger data capture.

> Adam
> September 21, 2015 at 10:17 PM
> Hi, sorry for the rather amateur question, I’ve set the script up in a Amazon MC2 instance and is running perfectly in terms of connecting and retrieving data from Google and Bing, however I am completely lost when it comes to set up cronjob, could you show me know how to set it up please? Thanks in advance :)
> ---
> 
> Brian
> September 21, 2015 at 10:55 PM
> Adam,
> 
> Implementing a cronjob is something that has been on my todo list but I have not actually tested or fully built out yet at this time. My intentions are to have the ability to make one cron task run and it would import all of the scripts – much like the “Import All” button on the Data Capture screen. Sadly, that was implemented via Javascript and I don’t feel there would be a way to make that work quickly/easily.
> 
> But you should be able to run a cronjob on this currently, you’ll just need to implement one cronjob per domain and search engine you wish to capture. I was just working on adding some documentation to the wiki this morning around how to do this. The page is incomplete at this time, but there should be enough information for you to get the basics working.
> https://github.com/PromInc/organic-search-analytics/wiki/Import-Parameters
> 
> It’s pretty straight forward though – make your cronjob call the data-capture-run.php script with the correct query parameter set and you should be all set to go.
> 
> A few things to keep in mind though – Google typically offers data from 3-4 days prior to today. That’s why in the GUI you’ll see that the most recent date you can ever import is 4 days old. So when writing your cronjob ensure that you set the date offset correctly to account for this.
> 
> Bing provides ALL of their data in one feed which is reported on a weekly basis – not daily like Google. The Bing import script does account for the long list of data and only imports new/missing data, so there are not duplicates. But because of this, a date is required to be passed to the data-capture-run.php script however it’s actually irrelevant. So any date works.
> 
> I think that should be all of the information you’d need to get this setup. Like I said, this isn’t a fully vetted out solution as you’ll need multiple cronjobs but it should work at this time. I’m always working on improving the tool, so if you have any suggestions or wish to contribute to the code base I’m open to anything you’d be willing to offer! This is a project that I’m building to replace some overly large Excel spreadsheets and make my efforts easier – I figured it was worth sharing with the community!
> ---
> 
> Adam
> September 22, 2015 at 2:11 PM
> Wow, thanks for the pointers! I certainly will give it a try. You are my rock star!
> ---
> 
> Brian
> September 22, 2015 at 5:44 PM
> Good to hear!
> 
> I love feedback, so thanks for the comments.
> 
> I’ve updated the Wiki pages on GitHub yesterday.
> 
> I’m also working on some nice updates to the reporting portion of the tool – I don’t have a timeline of when those will be released, but they are coming together nicely and make this much more valuable.
> 
> Always so much to do and so little time…
> ---
> 
> Adam
> September 24, 2015 at 9:36 PM
> Hi Brian:
> 
> I’ve had a look today, am I right in thinking in order to set up cronjob for automation, the data-capture-run.php will need to be modified as the arguments passed over by cron can only be captured by $_SERVER[‘argv’][1];? is there any more elegant interim solutions you could recommend?
> ---
> 
> Brian
> September 28, 2015 at 6:18 PM
> Adam,
> Sadly I don’t have the capacity at the moment to setup and test a CRON scenario.
> 
> But I wasn’t aware that [passing GET parameters via CRON](http://stackoverflow.com/questions/11297945/passing-get-paramaters-to-cron-job) is different than a web browser request.
> 
> I think you are right that the script will need to be modified to make this work. I would like this change to be a part of the repository however, so I’m hoping that you can help in ensuring this is all configured correctly.
> 
> I have modified data-capture-run.php to accommodate this needed change on a new branch – [CRON Functionality](https://github.com/PromInc/organic-search-analytics/tree/CRON-Functionality). FYI – I’m not sure what happened, but I think that branch may have some older code in it… I suggest only downloading the data-capture-run.php file from that branch and updating your local copy.
> 
> One concern I’ve had about calling this via a CRON is the 4 day offset required for the date to trigger a Google request – can you confirm that this is capable via CRON? If not, I may have to add another parameter that allows triggering the request without having the date set.
> 
> I know others have done some programatic calls to this utility and having the CRON piece available and a part of the repository is valuable. For that reason, as well as keeping all details in one location, I’d like for this conversation to be a part of the GitHub repository. I’ve opened an issue for this matter and would appreciate if we could continue this conversation there. [Github Issue #7 – CRON Functionality0{https://github.com/PromInc/organic-search-analytics/issues/7}
> 
> Thanks Adam for your help on this!

**Comment by code-kiddie** [comment]
Hi Brian:

Thanks for taking this up as quickly. I've done some test in fact just a moment ago, I approached it differently - albeit not as elegant, and will require twice the effect when it comes to future code updates/maintenance, but it's a quick and simple way to get this working. 

I created new file randomly named it data-capture-run-cron.php :), in it made some changes to capture the arguments passed on from cron command. Only two arguments I have decided to pass from cron command - Type and Domain - for now. The reason I omitted the Date is because I don't have a clue how to pass date as a argument in the specified format. So I moved it into the php script to generate that and assumed that I will always want to get the data from the 4th day prior.

Going forward, it might be worth creating a configuration page for cronjob, and read all the parameters from there directly rather than using cron command to pass the arguments.

Regarding to the Date, I assume it's not a range here, is it? If it's not a range, then am I right in thinking a loop is needed if it were to extract for a date range? Also, if there's more than one domain, then a loop may be required as well. Perhaps Date range and Domains can be read from a predefined configuration file?

I'll upload the new file shortly just to give you an idea what I meant above, but it is by no means a finished solution, a work in progress only.

Thanks
Liang (Adam is my forum name :))

**Comment by PromInc** [comment]
Liang,
Thanks for sharing how you've solved the issue.  I was toying with if a second file was needed or not.  Your comments make me think there is a need for it.

I like the idea of adding CRON options to the configuration.  Then you could make a very simple request and the tool will know what it should be performing.

I know it's possible to format a date in a CRON job in the proper format, however I'm not sure that it can be offset.

In the GUI there is a button to import all pending data captures - and yes, that does perform a loop.  It sends one request at a time.  While I'm sure that it could handle multiple concurrently, I figured doing them one by one would be a bit more safe and reliable.

So yes, I think it would be necessary to mimic that logic into the CRON tasks - process each domain one at a time.

Regarding the date - no, it is not designed to be a range.  That said, the Google API does allow for a range, but this tool sets the start and end date to the same date in the request.  This is for two reasons:
1. A maximum of 5,000 records can be captured from Google at once.  For large sites, there maybe more than 5,000 records in a given day, and thus I'm trying to maximize the amount of data that can be captured.
2. Daily data is the most granular that can be captured from Google - therefore I want to capture it at that level and it can be rolled up into more broad ranges in the reporting.  This functionality is coming soon...  I get distracted from finishing that task all too often lately...

Bing is a bit different - when you make an API request you get all historical data available.  In my testing I was seeing data back to March of 2013 I believe (lower trafficked site).  So not sure how far back their feed goes, or if it's a file-sized limit or what (not documented by Bing).  Regardless, their data is provided at a weekly granularity.  So that's the best we can see for their data.  Also, because all of the data is in this API request, the date passed to the data-capture-run.php request is irrelevant but required by the code to be a valid request.

Ok, enough rambling.  I'll look for your code as I'd like to use it as inspiration on how to best approach adding the CRON options.  I'll add this to a todo list for the future.
