### ISSUE TITLE
PHP 7.0.20 

### ISSUE THREAD

**Issue by bmbraga** [PromInc/organic-search-analytics#70]
Does not work in php 7?
I'm having this error:
PHP Fatal error:  Uncaught Error: Call to a member function query() on string in /home/public_html/_sa/inc/code/mysql.php:118\nStack trace:\n#0 /home/public_html/_sa/inc/code/mysql.php(173): MySQL->query('SELECT id,value...')\n#1 /home/public_html/_sa/settings.php(11): MySQL->getSettings('sites_google')\n#2 {main}\n  thrown in /home/public_html/_sa/inc/code/mysql.php on line 118, referer: https://www.com/_sa/index.php

**Comment by PromInc** [comment]
@bmbraga Can you please explain why did you closed this issue?  Does the error exist on PHP7?  (I haven't had a chance to test but would love for this to be compatible with the new standard and it's worth accurately documenting the issues so they can be resolved)

**Comment by bmbraga** [comment]
Hi, how are you? I was not mistaken. I just saved the config file and the file was not saved due to chown and I did not realize why the error was not shown.
After much debugging I saw that the bank ip was wrong.
Thank you and sorry for the inconvenience.
